#!/bin/bash

# A bash pipeline workflow for reference guided assembly.

# Default parameters
INPUT_DIR="" # Input directory
OUTPUT_DIR="" # Output directory
REFERENCE="" # Reference genome file
THREADS=4 # Default number of threads
max_length=2000 # Default maximum read length
min_length=100 # Default minimum read length

# Function to display help
show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -i  Input directory containing barcode folders with FASTQ files"
    echo "  -o  Output directory for processed data"
    echo "  -r  Reference genome file path"
    echo "  -t  Number of threads (default: 4)"
    echo "  -m  Maximum read length (default: 2000)"
    echo "  -l  Minimum read length (default: 100)"
    echo "  -h  Display this help and exit"
}

# Parse command-line options
while getopts ":hi:o:r:p:t:m:l:" opt; do
    case ${opt} in
        i ) INPUT_DIR=$OPTARG ;;
        o ) OUTPUT_DIR=$OPTARG ;;
        r ) REFERENCE=$OPTARG ;;
        t ) THREADS=$OPTARG ;;
        m ) max_length=$OPTARG ;;
        l ) min_length=$OPTARG ;;
        h ) show_help
            exit 0 ;;
        \? ) echo "Invalid option: $OPTARG" 1>&2
             show_help
             exit 1 ;;
        : ) echo "Invalid option: $OPTARG requires an argument" 1>&2
            show_help
            exit 1 ;;
    esac
done

# Validate required inputs
if [ -z "$INPUT_DIR" ] || [ -z "$OUTPUT_DIR" ] || [ -z "$REFERENCE" ] ; then
    echo "Error: Missing required arguments"
    show_help
    exit 1
fi

# Ensure the output and log directories exist
mkdir -p "$OUTPUT_DIR"
LOG_DIR="$OUTPUT_DIR/logs"
mkdir -p "$LOG_DIR"

# Process each barcode folder
for barcode_dir in "$INPUT_DIR"/*; do
    if [ -d "$barcode_dir" ]; then
        barcode=$(basename "$barcode_dir")
        barcode_output_dir="$OUTPUT_DIR/$barcode"
        mkdir -p "$barcode_output_dir"

        echo "Concatenate FASTQ files"
        cat "$barcode_dir"/*.fastq > "$barcode_output_dir/$barcode.fastq"
        
        echo "Run FastQC before trimming"
        fastqc -t $THREADS "$barcode_output_dir/$barcode.fastq" -o "$barcode_output_dir"

        echo "Quality control with fastp"
        fastp -i "$barcode_output_dir/$barcode.fastq" -o "$barcode_output_dir/${barcode}_filt.fastq" -q 8 -A -w $THREADS --length_limit $max_length -l $min_length -j "$LOG_DIR/${barcode}_fastp.json" -h "$LOG_DIR/${barcode}_fastp.html"
         
        echo "Run FastQC after trimming"
        fastqc -t $THREADS "$barcode_output_dir/${barcode}_filt.fastq" -o "$barcode_output_dir"

        echo "Align reads with minimap2"
        minimap2 -a -x map-ont -t $THREADS $REFERENCE "$barcode_output_dir/${barcode}_filt.fastq" | samtools view -bS -F 4 - | samtools sort -o "$barcode_output_dir/$barcode.sorted.bam" 
        samtools index "$barcode_output_dir/$barcode.sorted.bam"
        
        echo "Calculating depth"
        samtools depth "$barcode_output_dir/$barcode.sorted.bam" > "$barcode_output_dir/$barcode.depth.txt"
        awk '{sum+=$3} END {print "Average Depth:", sum/NR}' "$barcode_output_dir/$barcode.depth.txt"
        bedtools genomecov -ibam "$barcode_output_dir/$barcode.sorted.bam" > "$barcode_output_dir/$barcode.coverage.txt"
                
        echo "Variant calling with long-shot"
        longshot --bam "$barcode_output_dir/$barcode.sorted.bam" --ref $REFERENCE --no_haps --min_cov 50 --out "$barcode_output_dir/$barcode.longshot.vcf" 
        bgzip -c "$barcode_output_dir/$barcode.longshot.vcf" > "$barcode_output_dir/$barcode.longshot.vcf.gz"
        tabix "$barcode_output_dir/$barcode.longshot.vcf.gz"       

        echo "Activating Clair3 environment"
        source activate clair3

        echo "variant calling with clair3"
        run_clair3.sh -b "$barcode_output_dir/$barcode.sorted.bam" -f $REFERENCE -p ont -m /data/Bhagya/miniconda3/envs/clair3/bin/models/r941_prom_sup_g5014/ -t 20  -o "$barcode_output_dir/$barcode.clair3_output.vcf" --include_all_ctgs --haploid_precise --no_phasing_for_fa --min_coverage=50    
        echo "Deactivating Clair3 environment"
        conda deactivate
         
        echo "gunzip and indexing"
        gunzip "$barcode_output_dir/$barcode.clair3_output.vcf/merge_output.vcf.gz"
        mv "$barcode_output_dir/$barcode.clair3_output.vcf/merge_output.vcf" "$barcode_output_dir/$barcode.clair3.vcf"
        bgzip -c "$barcode_output_dir/$barcode.clair3.vcf" > "$barcode_output_dir/$barcode.clair3.vcf.gz"
        tabix "$barcode_output_dir/$barcode.clair3.vcf.gz"

        echo "Coverage analysis with bedtools"
        bedtools genomecov -bga -ibam "$barcode_output_dir/$barcode.sorted.bam" -g $REFERENCE | awk '$4 < 50' | bedtools merge > "$barcode_output_dir/$barcode.mask.bed"
        cp "$barcode_output_dir/$barcode.mask.bed" "$LOG_DIR/${barcode}_coverage.bed"

        echo "Generate consensus"
        bcftools consensus -f $REFERENCE "$barcode_output_dir/$barcode.clair3.vcf.gz" > "$barcode_output_dir/$barcode.preconsensus.fasta"

        echo "Mask low-coverage regions in the consensus"
        bedtools maskfasta -fi "$barcode_output_dir/$barcode.preconsensus.fasta" -bed "$barcode_output_dir/$barcode.mask.bed" -fo "$barcode_output_dir/$barcode.BCF.consensus.fasta"

        echo "Rename the FASTA headers to include the barcode name"
        sed -E "s/>/>$barcode-/" "$barcode_output_dir/$barcode.BCF.consensus.fasta" > "$barcode_output_dir/$barcode.final.consensus.fasta"
        
        echo "$barcode processing completed."
    else
        echo "$barcode.sorted.bam not found."
    fi
done
# Run MultiQC to aggregate results into a single report for all barcodes
multiqc "$LOG_DIR" -o "$OUTPUT_DIR"

echo "All barcodes processed. MultiQC report generated."
